// <auto-generated />
using System;
using CityManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Core.Entity_Classes.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("37dc186d-763c-4854-bd8e-f087c91fcf0e"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityId = new Guid("b2c3d4e5-f6a7-8901-bcde-f1234567890a"),
                            CityName = "Chicago"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
